# fly.toml app configuration file generated for nerd-trivia-3000-v5 on 2024-12-22T09:25:29+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nerd-trivia-3000-v5'
primary_region = 'atl'

[build]
  build_args = { NEXT_PUBLIC_POCKETBASE_URL = "NEXT_PUBLIC_POCKETBASE_URL" }


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
